- name: create user n
  tags: base
  ansible.builtin.user:
    name: n
    groups: "{{ 'root' if ansible_os_family != 'Debian' else 'sudo' }}"
    append: yes

- name: add ssh key for n
  tags: base
  ansible.builtin.authorized_key:
    user: n
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILQJiBJ3gKBhu0rtY1gqNLeZqUrl1BzkBdQnaJLJjN/a thenickstrick"

- name: deploy sshd_config template
  tags: base
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    mode: '0600'
  notify: restart ssh

- name: add nopasswd sudoers config
  tags: base
  ansible.builtin.copy:
    src: nopasswd
    dest: /etc/sudoers.d/nopasswd
    owner: root
    group: root
    mode: 0440

- name: apply sysctl configuration
  tags: base
  template: 
    src: sysctl_conf.j2
    dest: /etc/sysctl.conf
    mode: '0644'
  notify: reload sysctl

- name: install base utilities
  tags: base
  package:
    name:
      - btop
      - ca-certificates
      - curl
      - git
      - gpg
      - htop
      - jq
      - net-tools
      - rsync
      - vim
      - wget
    state: present
    update_cache: yes
