- name: create user n
  tags: always
  ansible.builtin.user:
    name: n
    groups: root

- name: add nopasswd sudoers config
  tags: always
  ansible.builtin.copy:
    src: nopasswd
    dest: /etc/sudoers.d/nopasswd
    owner: root
    group: root
    mode: 0440

- name: add ssh key for n
  tags: always
  ansible.builtin.authorized_key:
    user: n
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILQJiBJ3gKBhu0rtY1gqNLeZqUrl1BzkBdQnaJLJjN/a thenickstrick"
