---
- hosts: pve

  vars_files:
    - pve-nag-buster-vars.yml

  tasks:

    - name: Copy scripts directory to remote hosts
      copy:
        src: pve-nag-buster/
        dest: /root/pve-nag-buster
        mode: a+x

    - name: Run install.sh
      shell: "/root/pve-nag-buster/install.sh --install"

    - name: Remove scripts directory
      file:
        path: /root/pve-nag-buster
        state: absent