- name: add dockers signing key
  ansible.builtin.shell: |
    curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc
  args:
    creates: /etc/apt/keyrings/docker.asc
  when: ansible_os_family == 'Debian'

- name: add dockers apt repository
  ansible.builtin.shell: 
    "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian \
    $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
    sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
  args:
    creates: /etc/apt/sources.list.d/docker.list
  when: ansible_os_family == 'Debian'

- name: udpate apt cache
  ansible.builtin.apt:
    update_cache: yes
  when: ansible_os_family == 'Debian'

- name: install docker packages
  ansible.builtin.apt:
    name:
      - docker-ce 
      - docker-ce-cli 
      - containerd.io 
      - docker-buildx-plugin 
      - docker-compose-plugin
    state: present
  when: ansible_os_family == 'Debian'

- name: add users to docker group
  ansible.builtin.user:
    name: n
    groups: docker
    append: yes
