- name: add dockers signing key
  tags: docker
  ansible.builtin.shell: |
    curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc
  args:
    creates: /etc/apt/keyrings/docker.asc
  when: ansible_os_family == 'Debian'

- name: add dockers apt repository
  tags: docker
  ansible.builtin.lineinfile: 
    path: /etc/apt/sources.list.d/docker.list
    line: deb [arch={{ architecture_mapping[ansible_architecture] | default(ansible_architecture) }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian {{ ansible_lsb.codename }} stable
    create: yes
    state: present
  vars:
    architecture_mapping:
      x86_64: amd64
      aarch64: arm64
      armv7l: armhf
  when: ansible_os_family == 'Debian'

- name: udpate apt cache
  tags: docker
  ansible.builtin.apt:
    update_cache: yes
  when: ansible_os_family == 'Debian'

- name: install docker packages
  tags: docker
  ansible.builtin.apt:
    name:
      - docker-ce 
      - docker-ce-cli 
      - containerd.io 
      - docker-buildx-plugin 
      - docker-compose-plugin
    state: present
  when: ansible_os_family == 'Debian'

- name: add users to docker group
  tags: docker
  ansible.builtin.user:
    name: n
    groups: docker
    append: yes
