- name: apply base role to all hosts
  hosts: all
  become: true
  roles:
    - role: base
      tags: base

- name: setup docker role on docker hosts
  hosts: d
  become: true
  roles:
    - role: docker
      tags: docker

- name: setup kubernetes role on k8s hosts
  hosts: k
  become: true
  roles:
    - role: kubernetes
      tags: kubernetes
