---
- hosts: all
  become: true
  tasks:
    - name: Set package manager and update options based on OS
      set_fact:
        package_manager: "{{ 'ansible.builtin.apt' if ansible_distribution in ['Debian', 'Ubuntu'] else 'ansible.builtin.dnf' }}"
        update_params: >
          {{
            {'upgrade': 'dist', 'update_cache': True} 
            if ansible_distribution in ['Debian', 'Ubuntu'] 
            else {'update_only': True, 'update_cache': True}
          }}

    - name: Install updates
      tags: always
      ansible.builtin.include_role:
        name: "{{ package_manager }}"
      with_items:
        - "{{ update_params }}"

# - hosts: all
#   become: true
#   roles: 
#     - base
