---
- hosts: all
  become: true
  tasks:
    - name: Install updates on Debian/Ubuntu
      ansible.builtin.apt:
        upgrade: dist
        update_cache: yes
      when: ansible_distribution in ['Debian', 'Ubuntu']
      tags: always

    - name: Install updates on Fedora
      ansible.builtin.dnf:
        update_only: yes
        update_cache: yes
      when: ansible_distribution == "Fedora"
      tags: always

# - hosts: all
#   become: true
#   roles: 
#     - base
